#!/bin/bash -e

echo "You will be prompted to enter some fields. Enter \`.\` for them all, except the following:"
echo "  Organization Name (eg, company) []:boomclap"
echo "  Organizational Unit Name (eg, section) []:local dev server"
echo ""

PEMFILE="local-dev-server.pem"
openssl req -new -x509 -keyout $PEMFILE -out $PEMFILE -days 30 -nodes
